AllCops:
    NewCops: enable

Metrics/BlockLength:
  Exclude: 
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
