AllCops:
    NewCops: enable

Metrics/BlockLength:
  Exclude: 
    - spec/**/*

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WordArray:
  EnforcedStyle: brackets
